// for every public class in java it creates byte files
// Compile Java File --> javac test.java
/* Execute java class ---> java test (when executing JVM will check if main method is there,
 if not will get error : main method not found ) */
// Always in Java the class name should be same as file name
public class test {
    public static void main(String[] args){
        System.out.println("good Morning");
    }
} 